#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Acme\Console\Command\GreetCommand;
use Spatie\Commands\ResolveCommand;
use Symfony\Component\Console\Application;

$application = new Application('SSL certificate chain resolver', '0.1.0');
$application->add(new ResolveCommand());
$application->run();