#!/usr/bin/env php
<?php
// application.php

use Acme\Console\Command\GreetCommand;
use Spatie\Commands\ResolveCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    require __DIR__.'/vendor/autoload.php';
}
else
{
    require __DIR__.'/../../autoload.php';
}

$application = new Application('SSL certificate chain resolver', '0.1.0');

$resolveCommand = new ResolveCommand();

$application->add($resolveCommand);

$application->setDefaultCommand($resolveCommand->getName());

$application->run();