#! /usr/bin/env php

<?php
// application.php

use Spatie\Commands\ResolveCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    require __DIR__.'/vendor/autoload.php';
}
else
{
    require __DIR__.'/../../autoload.php';
}

$application = new Application('SSL certificate chain resolver', '1.0.2');

$application->add(new ResolveCommand());

$application->run();
